# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 00:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=50)),
                ('Descripcion_Categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Foto', models.CharField(default='Sin titulo', max_length=50)),
                ('Descripcion_Foto', models.CharField(blank=True, max_length=200)),
                ('Fecha_Foto', models.DateField(auto_now_add=True)),
                ('Archivo_Foto', models.ImageField(upload_to='Fotos/')),
                ('Autor_Foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(blank=True, to='crudfinal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voto_Puntuacion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Comentario_Puntuacion', models.CharField(blank=True, max_length=200)),
                ('Autor_Puntuacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudfinal.Foto')),
            ],
        ),
    ]
