# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudfinal', '0002_auto_20161117_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='Archivo_Foto',
            field=models.ImageField(upload_to='media/Fotos/'),
        ),
    ]
