# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudfinal', '0003_auto_20161117_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='Nombre_Foto',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
    ]
